[package]
name = "rustdi"
version = "0.1.0"
authors = ["Nico Burns <nico@nicoburns.com>"]

[lib]
name = "rustdi"
path = "src/lib.rs"

[dependencies]
typemap = "0.3.3"
futures = "0.1"
rustdi_derive = { version = "0.1", path = "../rustdi_derive" }

